title: JTD
description: Jeykll site using the Just the Docs theme with Jekyll-Scholar plugin
theme: just-the-docs

url: https://geoffrowland.github.io/jtd/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
    - jekyll-scholar

